import type { PresetDto } from "../../types/presets";
import type { DateMode, EpisodeScanResult, EpisodeSortKey, OptimizerRangeGroupKey, OptimizerRangeGroupStatus, OptimizerRangeRankMetric, OptimizerResultRow, PaperArbActiveRow, PaperArbAnalyticsResponse, PaperArbCloseMode, PaperArbClosedDto, PaperArbDilutionMode, PaperArbMetric, PaperArbOptimizerRangesResponse, PaperArbPnlMode, PaperArbPriceMode, PaperArbRatingBand, PaperArbRatingMode, PaperArbRatingRule, PaperArbRatingType, PaperArbSession, PaperArbSizingMode, PaperListMode, ScopePanelKey, ScopeOptimizerBinMode, ScopeResearchDraft, ScopeResearchSelection, SharedRangeFilterKey, SharedRangeFilterMode, SortDir, TabKey, TriMode, ZapMode } from "./types";

/**
 * Every piece of filter/view state a scanner holds, and the one thing that is genuinely shared
 * between strategies.
 *
 * Derived mechanically from the two scanner components rather than written by hand: of their
 * state fields, 226 are common, ZERO are Arbitrage-only, and 17 belong to OpenDoor alone (its
 * exit class, the three parameter gates, the up/down levels and its snapshot loading state).
 * Those 17 are the strategy's own — see `ScannerStrategyParams` in ./strategy.
 *
 * Exactly one shared field disagrees on its default: startAbs is 0.1 for Arbitrage and 0 for
 * OpenDoor, which is what `defaults` on the descriptor is for.
 */
export type ScannerFilterState = {
  activeRows: PaperArbActiveRow[];
  addDelayMinutes: number;
  analytics: PaperArbAnalyticsResponse | null;
  analyticsSort: { key: EpisodeSortKey; dir: SortDir };
  arbitrageTickerMetaByTicker: 
    Record<string, { corr?: number | null; beta?: number | null; sigma?: number | null; sectorL3?: string | null; benchTicker?: string | null }>
  ;
  arbitrageTickerMetaLoading: boolean;
  benchTickersText: string;
  closeMode: PaperArbCloseMode;
  countryEnabled: TriMode;
  dateFrom: string;
  dateMode: DateMode;
  dateNy: string;
  dateTo: string;
  days: string[];
  dilutionMode: PaperArbDilutionMode;
  dilutionStep: number;
  endAbs: number;
  /**
   * ENTRY STOP: after this time no new positions are taken, leaving CUTOFF free to also serve as
   * the exit trigger. Empty means "not set" — the caller falls back to startCutoffTime, exactly
   * the way the panel already reads it (see ExecutionSettingsPanel's entryStopValue).
   */
  entryStopTime: string;
  episodesRows: PaperArbClosedDto[];
  episodesSort: { key: EpisodeSortKey; dir: SortDir };
  equityCurveMode: "Daily" | "Trade";
  err: string | null;
  exchangeEnabled: TriMode;
  excludeCrap: boolean;
  excludeItb: boolean;
  setExcludeItb: (v: boolean | ((p: boolean) => boolean)) => void;
  excludeHard: boolean;
  setExcludeHard: (v: boolean | ((p: boolean) => boolean)) => void;
  excludeCorr: boolean;
  setExcludeCorr: (v: boolean | ((p: boolean) => boolean)) => void;
  excludeDividend: boolean;
  excludeETF: boolean;
  excludeHasNews: boolean;
  excludeHasReport: boolean;
  excludePTP: boolean;
  excludeSSR: boolean;
  ignoreTickersText: string;
  imbExchsText: string;
  includeChina: boolean;
  includeEquityCurve: boolean;
  includeUSA: boolean;
  internalRuleBand: PaperArbRatingBand;
  internalSession: PaperArbSession;
  internalTab: TabKey;
  listMode: PaperListMode;
  loading: boolean;
  maxAdds: number;
  maxAdv20: string;
  maxAdv20NF: string;
  maxAdv90: string;
  maxAdv90NF: string;
  maxAvPostMhVol90NF: string;
  maxAvPreMhValue20NF: string;
  maxAvPreMhValue90NF: string;
  maxAvPreMhVol90NF: string;
  maxAvPreMhv: string;
  maxAvgDailyValue20: string;
  maxAvgDailyValue90: string;
  maxBeta: string;
  maxClsToClsPct: string;
  maxCorr: string;
  maxGap: string;
  maxGapPct: string;
  maxImbARCA: string;
  maxImbExch1555: string;
  maxImbExch925: string;
  maxImbExchValue: string;
  maxLo: string;
  maxLstCls: string;
  maxLstClsNewsCnt: string;
  maxLstPrcL: string;
  maxLstPrcLstClsPct: string;
  maxMarketCapM: string;
  maxMdnPostMhVol90NF: string;
  maxMdnPreMhVol90: string;
  maxNewsCnt: string;
  maxPreMhBidLstPrcPct: string;
  maxPreMhHiLstClsPct: string;
  maxPreMhLoLstClsPct: string;
  maxPreMhLoLstPrcPct: string;
  maxPreMhMDV20NF: string;
  maxPreMhMDV90NF: string;
  maxPreMktVol: string;
  maxPreMktVolNF: string;
  maxRoundLot: string;
  maxSigma: string;
  /** The pair's ALPHA — its median converged peak. Fourth of the pair statistics. */
  maxAlpha: string;
  maxSpread: string;
  maxSpreadBps: string;
  maxTCls: string;
  maxTierBp: string;
  maxVWAP: string;
  maxVolNFfromLstCls: string;
  maxVolRel: string;
  maxVolatility20: string;
  maxVolatility90: string;
  maxYCls: string;
  metric: PaperArbMetric;
  minAdv20: string;
  minAdv20NF: string;
  minAdv90: string;
  minAdv90NF: string;
  minAvPostMhVol90NF: string;
  minAvPreMhValue20NF: string;
  minAvPreMhValue90NF: string;
  minAvPreMhVol90NF: string;
  minAvPreMhv: string;
  minAvgDailyValue20: string;
  minAvgDailyValue90: string;
  minBeta: string;
  minClsToClsPct: string;
  minCorr: string;
  minGap: string;
  minGapPct: string;
  minHoldCandles: number;
  minImbARCA: string;
  minImbExch1555: string;
  minImbExch925: string;
  minImbExchValue: string;
  minLo: string;
  minLstCls: string;
  minLstClsNewsCnt: string;
  minLstPrcL: string;
  minLstPrcLstClsPct: string;
  minMarketCapM: string;
  minMdnPostMhVol90NF: string;
  minMdnPreMhVol90: string;
  minNewsCnt: string;
  minPreMhBidLstPrcPct: string;
  minPreMhHiLstClsPct: string;
  minPreMhLoLstClsPct: string;
  minPreMhLoLstPrcPct: string;
  minPreMhMDV20NF: string;
  minPreMhMDV90NF: string;
  minPreMktVol: string;
  minPreMktVolNF: string;
  minRoundLot: string;
  minSigma: string;
  minAlpha: string;
  minSpread: string;
  minSpreadBps: string;
  minTCls: string;
  minTierBp: string;
  minVWAP: string;
  minVolNFfromLstCls: string;
  minVolRel: string;
  minVolatility20: string;
  minVolatility90: string;
  minYCls: string;
  offset: number;
  optimizerBucketCount: number;
  optimizerBinMode: ScopeOptimizerBinMode;
  optimizerErr: string | null;
  optimizerLoading: boolean;
  optimizerProgress: { done: number; total: number };
  optimizerRangeGroupHidden: Record<OptimizerRangeGroupKey, boolean>;
  optimizerRangeGroupStatus: Record<OptimizerRangeGroupKey, OptimizerRangeGroupStatus>;
  optimizerRangeMinTrades: number;
  optimizerRangeRankMetric: OptimizerRangeRankMetric;
  optimizerRanges: PaperArbOptimizerRangesResponse | null;
  optimizerRangesErr: string | null;
  optimizerRangesLoading: boolean;
  optimizerRows: OptimizerResultRow[];
  optimizerStatsHidden: boolean;
  pnlMode: PaperArbPnlMode;
  preStartTime: string;
  priceMode: PaperArbPriceMode;
  qSide: "" | "Long" | "Short";
  qTicker: string;
  rangePreset: "3d" | "5d" | "10d" | "15d" | "20d" | "30d";
  ratingEnabledBands: Record<PaperArbRatingBand, boolean>;
  ratingMode: PaperArbRatingMode;
  ratingRules: PaperArbRatingRule[];
  ratingType: PaperArbRatingType;
  requireHasNews: boolean;
  requireHasReport: boolean;
  requireIsCrap: boolean;
  requireIsETF: boolean;
  requireIsPTP: boolean;
  requireIsSSR: boolean;
  scanEndMax: number;
  scanEndMin: number;
  scanEndStep: number;
  scanErr: string | null;
  scanLoading: boolean;
  scanObjective: "pnl" | "winrate";
  scanProgress: { done: number; total: number };
  scanRows: EpisodeScanResult[];
  scanStartMax: number;
  scanStartMin: number;
  scanStartStep: number;
  scanTopK: number;
  scannerPresetBusy: boolean;
  scannerPresetDraftName: string;
  scannerPresetSaveMode: boolean;
  scannerPresetStatus: string;
  scannerPresets: PresetDto[];
  scopeBenchText: string;
  scopeFullscreenPanel: ScopePanelKey | null;
  scopeMode: "ALL" | "TOP";
  scopeParameterGroupExpanded: Record<string, boolean>;
  scopeResearchDrafts: Record<ScopePanelKey, ScopeResearchDraft>;
  scopeResearchFiltersHidden: 
    Record<ScopePanelKey, { extra: boolean; parallel: boolean }>
  ;
  scopeResearchSelections: Record<ScopePanelKey, ScopeResearchSelection | null>;
  scopeSelectedParameterKeys: string[];
  sectorEnabled: TriMode;
  selCountries: Set<string>;
  selExchanges: Set<string>;
  selSectors: Set<string>;
  sharedRangeFilterModes: Record<SharedRangeFilterKey, SharedRangeFilterMode>;
  showAdvanced: boolean;
  showApply: boolean;
  showIgnore: boolean;
  showPin: boolean;
  showPresets: boolean;
  showSharedMinMax: boolean;
  sideFilter: "" | "Long" | "Short";
  sizeValue: number;
  sizingMode: PaperArbSizingMode;
  startAbs: number;
  startAbsMax: string;
  startCutoffTime: string;
  streamAutoStartLocked: boolean;
  streamAutomationTogglePending: null | "start" | "stop";
  streamSortKey: "alpha" | "sigma" | "netEdge";
  streamWindowCaptureBusy: boolean;
  tickersText: string;
  topBenchOn: boolean;
  topMode: boolean;
  topN: number;
  topSigmaOn: boolean;
  topTimeOn: boolean;
  updatedAt: Date | null;
  zapMode: ZapMode;
};

/** Setters, named as the components already name them, so the migration is a rename-free lift. */
export type ScannerFilterSetters = {
  setActiveRows: React.Dispatch<React.SetStateAction<PaperArbActiveRow[]>>;
  setAddDelayMinutes: React.Dispatch<React.SetStateAction<number>>;
  setAnalytics: React.Dispatch<React.SetStateAction<PaperArbAnalyticsResponse | null>>;
  setAnalyticsSort: React.Dispatch<React.SetStateAction<{ key: EpisodeSortKey; dir: SortDir }>>;
  setArbitrageTickerMetaByTicker: React.Dispatch<React.SetStateAction<
    Record<string, { corr?: number | null; beta?: number | null; sigma?: number | null; sectorL3?: string | null; benchTicker?: string | null }>
  >>;
  setArbitrageTickerMetaLoading: React.Dispatch<React.SetStateAction<boolean>>;
  setBenchTickersText: React.Dispatch<React.SetStateAction<string>>;
  setCloseMode: React.Dispatch<React.SetStateAction<PaperArbCloseMode>>;
  setCountryEnabled: React.Dispatch<React.SetStateAction<TriMode>>;
  setDateFrom: React.Dispatch<React.SetStateAction<string>>;
  setDateMode: React.Dispatch<React.SetStateAction<DateMode>>;
  setDateNy: React.Dispatch<React.SetStateAction<string>>;
  setDateTo: React.Dispatch<React.SetStateAction<string>>;
  setDays: React.Dispatch<React.SetStateAction<string[]>>;
  setDilutionMode: React.Dispatch<React.SetStateAction<PaperArbDilutionMode>>;
  setDilutionStep: React.Dispatch<React.SetStateAction<number>>;
  setEndAbs: React.Dispatch<React.SetStateAction<number>>;
  setEntryStopTime: React.Dispatch<React.SetStateAction<string>>;
  setEpisodesRows: React.Dispatch<React.SetStateAction<PaperArbClosedDto[]>>;
  setEpisodesSort: React.Dispatch<React.SetStateAction<{ key: EpisodeSortKey; dir: SortDir }>>;
  setEquityCurveMode: React.Dispatch<React.SetStateAction<"Daily" | "Trade">>;
  setErr: React.Dispatch<React.SetStateAction<string | null>>;
  setExchangeEnabled: React.Dispatch<React.SetStateAction<TriMode>>;
  setExcludeCrap: React.Dispatch<React.SetStateAction<boolean>>;
  setExcludeDividend: React.Dispatch<React.SetStateAction<boolean>>;
  setExcludeETF: React.Dispatch<React.SetStateAction<boolean>>;
  setExcludeHasNews: React.Dispatch<React.SetStateAction<boolean>>;
  setExcludeHasReport: React.Dispatch<React.SetStateAction<boolean>>;
  setExcludePTP: React.Dispatch<React.SetStateAction<boolean>>;
  setExcludeSSR: React.Dispatch<React.SetStateAction<boolean>>;
  setIgnoreTickersText: React.Dispatch<React.SetStateAction<string>>;
  setImbExchsText: React.Dispatch<React.SetStateAction<string>>;
  setIncludeChina: React.Dispatch<React.SetStateAction<boolean>>;
  setIncludeEquityCurve: React.Dispatch<React.SetStateAction<boolean>>;
  setIncludeUSA: React.Dispatch<React.SetStateAction<boolean>>;
  setInternalRuleBand: React.Dispatch<React.SetStateAction<PaperArbRatingBand>>;
  setInternalSession: React.Dispatch<React.SetStateAction<PaperArbSession>>;
  setInternalTab: React.Dispatch<React.SetStateAction<TabKey>>;
  setListMode: React.Dispatch<React.SetStateAction<PaperListMode>>;
  setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  setMaxAdds: React.Dispatch<React.SetStateAction<number>>;
  setMaxAdv20: React.Dispatch<React.SetStateAction<string>>;
  setMaxAdv20NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxAdv90: React.Dispatch<React.SetStateAction<string>>;
  setMaxAdv90NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxAvPostMhVol90NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxAvPreMhValue20NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxAvPreMhValue90NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxAvPreMhVol90NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxAvPreMhv: React.Dispatch<React.SetStateAction<string>>;
  setMaxAvgDailyValue20: React.Dispatch<React.SetStateAction<string>>;
  setMaxAvgDailyValue90: React.Dispatch<React.SetStateAction<string>>;
  setMaxBeta: React.Dispatch<React.SetStateAction<string>>;
  setMaxClsToClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMaxCorr: React.Dispatch<React.SetStateAction<string>>;
  setMaxGap: React.Dispatch<React.SetStateAction<string>>;
  setMaxGapPct: React.Dispatch<React.SetStateAction<string>>;
  setMaxImbARCA: React.Dispatch<React.SetStateAction<string>>;
  setMaxImbExch1555: React.Dispatch<React.SetStateAction<string>>;
  setMaxImbExch925: React.Dispatch<React.SetStateAction<string>>;
  setMaxImbExchValue: React.Dispatch<React.SetStateAction<string>>;
  setMaxLo: React.Dispatch<React.SetStateAction<string>>;
  setMaxLstCls: React.Dispatch<React.SetStateAction<string>>;
  setMaxLstClsNewsCnt: React.Dispatch<React.SetStateAction<string>>;
  setMaxLstPrcL: React.Dispatch<React.SetStateAction<string>>;
  setMaxLstPrcLstClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMaxMarketCapM: React.Dispatch<React.SetStateAction<string>>;
  setMaxMdnPostMhVol90NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxMdnPreMhVol90: React.Dispatch<React.SetStateAction<string>>;
  setMaxNewsCnt: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMhBidLstPrcPct: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMhHiLstClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMhLoLstClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMhLoLstPrcPct: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMhMDV20NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMhMDV90NF: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMktVol: React.Dispatch<React.SetStateAction<string>>;
  setMaxPreMktVolNF: React.Dispatch<React.SetStateAction<string>>;
  setMaxRoundLot: React.Dispatch<React.SetStateAction<string>>;
  setMaxSigma: React.Dispatch<React.SetStateAction<string>>;
  setMaxAlpha: React.Dispatch<React.SetStateAction<string>>;
  setMaxSpread: React.Dispatch<React.SetStateAction<string>>;
  setMaxSpreadBps: React.Dispatch<React.SetStateAction<string>>;
  setMaxTCls: React.Dispatch<React.SetStateAction<string>>;
  setMaxTierBp: React.Dispatch<React.SetStateAction<string>>;
  setMaxVWAP: React.Dispatch<React.SetStateAction<string>>;
  setMaxVolNFfromLstCls: React.Dispatch<React.SetStateAction<string>>;
  setMaxVolRel: React.Dispatch<React.SetStateAction<string>>;
  setMaxVolatility20: React.Dispatch<React.SetStateAction<string>>;
  setMaxVolatility90: React.Dispatch<React.SetStateAction<string>>;
  setMaxYCls: React.Dispatch<React.SetStateAction<string>>;
  setMetric: React.Dispatch<React.SetStateAction<PaperArbMetric>>;
  setMinAdv20: React.Dispatch<React.SetStateAction<string>>;
  setMinAdv20NF: React.Dispatch<React.SetStateAction<string>>;
  setMinAdv90: React.Dispatch<React.SetStateAction<string>>;
  setMinAdv90NF: React.Dispatch<React.SetStateAction<string>>;
  setMinAvPostMhVol90NF: React.Dispatch<React.SetStateAction<string>>;
  setMinAvPreMhValue20NF: React.Dispatch<React.SetStateAction<string>>;
  setMinAvPreMhValue90NF: React.Dispatch<React.SetStateAction<string>>;
  setMinAvPreMhVol90NF: React.Dispatch<React.SetStateAction<string>>;
  setMinAvPreMhv: React.Dispatch<React.SetStateAction<string>>;
  setMinAvgDailyValue20: React.Dispatch<React.SetStateAction<string>>;
  setMinAvgDailyValue90: React.Dispatch<React.SetStateAction<string>>;
  setMinBeta: React.Dispatch<React.SetStateAction<string>>;
  setMinClsToClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMinCorr: React.Dispatch<React.SetStateAction<string>>;
  setMinGap: React.Dispatch<React.SetStateAction<string>>;
  setMinGapPct: React.Dispatch<React.SetStateAction<string>>;
  setMinHoldCandles: React.Dispatch<React.SetStateAction<number>>;
  setMinImbARCA: React.Dispatch<React.SetStateAction<string>>;
  setMinImbExch1555: React.Dispatch<React.SetStateAction<string>>;
  setMinImbExch925: React.Dispatch<React.SetStateAction<string>>;
  setMinImbExchValue: React.Dispatch<React.SetStateAction<string>>;
  setMinLo: React.Dispatch<React.SetStateAction<string>>;
  setMinLstCls: React.Dispatch<React.SetStateAction<string>>;
  setMinLstClsNewsCnt: React.Dispatch<React.SetStateAction<string>>;
  setMinLstPrcL: React.Dispatch<React.SetStateAction<string>>;
  setMinLstPrcLstClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMinMarketCapM: React.Dispatch<React.SetStateAction<string>>;
  setMinMdnPostMhVol90NF: React.Dispatch<React.SetStateAction<string>>;
  setMinMdnPreMhVol90: React.Dispatch<React.SetStateAction<string>>;
  setMinNewsCnt: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMhBidLstPrcPct: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMhHiLstClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMhLoLstClsPct: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMhLoLstPrcPct: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMhMDV20NF: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMhMDV90NF: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMktVol: React.Dispatch<React.SetStateAction<string>>;
  setMinPreMktVolNF: React.Dispatch<React.SetStateAction<string>>;
  setMinRoundLot: React.Dispatch<React.SetStateAction<string>>;
  setMinSigma: React.Dispatch<React.SetStateAction<string>>;
  setMinAlpha: React.Dispatch<React.SetStateAction<string>>;
  setMinSpread: React.Dispatch<React.SetStateAction<string>>;
  setMinSpreadBps: React.Dispatch<React.SetStateAction<string>>;
  setMinTCls: React.Dispatch<React.SetStateAction<string>>;
  setMinTierBp: React.Dispatch<React.SetStateAction<string>>;
  setMinVWAP: React.Dispatch<React.SetStateAction<string>>;
  setMinVolNFfromLstCls: React.Dispatch<React.SetStateAction<string>>;
  setMinVolRel: React.Dispatch<React.SetStateAction<string>>;
  setMinVolatility20: React.Dispatch<React.SetStateAction<string>>;
  setMinVolatility90: React.Dispatch<React.SetStateAction<string>>;
  setMinYCls: React.Dispatch<React.SetStateAction<string>>;
  setOffset: React.Dispatch<React.SetStateAction<number>>;
  setOptimizerBucketCount: React.Dispatch<React.SetStateAction<number>>;
  setOptimizerBinMode: React.Dispatch<React.SetStateAction<ScopeOptimizerBinMode>>;
  setOptimizerErr: React.Dispatch<React.SetStateAction<string | null>>;
  setOptimizerLoading: React.Dispatch<React.SetStateAction<boolean>>;
  setOptimizerProgress: React.Dispatch<React.SetStateAction<{ done: number; total: number }>>;
  setOptimizerRangeGroupHidden: React.Dispatch<React.SetStateAction<Record<OptimizerRangeGroupKey, boolean>>>;
  setOptimizerRangeGroupStatus: React.Dispatch<React.SetStateAction<Record<OptimizerRangeGroupKey, OptimizerRangeGroupStatus>>>;
  setOptimizerRangeMinTrades: React.Dispatch<React.SetStateAction<number>>;
  setOptimizerRangeRankMetric: React.Dispatch<React.SetStateAction<OptimizerRangeRankMetric>>;
  setOptimizerRanges: React.Dispatch<React.SetStateAction<PaperArbOptimizerRangesResponse | null>>;
  setOptimizerRangesErr: React.Dispatch<React.SetStateAction<string | null>>;
  setOptimizerRangesLoading: React.Dispatch<React.SetStateAction<boolean>>;
  setOptimizerRows: React.Dispatch<React.SetStateAction<OptimizerResultRow[]>>;
  setOptimizerStatsHidden: React.Dispatch<React.SetStateAction<boolean>>;
  setPnlMode: React.Dispatch<React.SetStateAction<PaperArbPnlMode>>;
  setPreStartTime: React.Dispatch<React.SetStateAction<string>>;
  setPriceMode: React.Dispatch<React.SetStateAction<PaperArbPriceMode>>;
  setQSide: React.Dispatch<React.SetStateAction<"" | "Long" | "Short">>;
  setQTicker: React.Dispatch<React.SetStateAction<string>>;
  setRangePreset: React.Dispatch<React.SetStateAction<"3d" | "5d" | "10d" | "15d" | "20d" | "30d">>;
  setRatingEnabledBands: React.Dispatch<React.SetStateAction<Record<PaperArbRatingBand, boolean>>>;
  setRatingMode: React.Dispatch<React.SetStateAction<PaperArbRatingMode>>;
  setRatingRules: React.Dispatch<React.SetStateAction<PaperArbRatingRule[]>>;
  setRatingType: React.Dispatch<React.SetStateAction<PaperArbRatingType>>;
  setRequireHasNews: React.Dispatch<React.SetStateAction<boolean>>;
  setRequireHasReport: React.Dispatch<React.SetStateAction<boolean>>;
  setRequireIsCrap: React.Dispatch<React.SetStateAction<boolean>>;
  setRequireIsETF: React.Dispatch<React.SetStateAction<boolean>>;
  setRequireIsPTP: React.Dispatch<React.SetStateAction<boolean>>;
  setRequireIsSSR: React.Dispatch<React.SetStateAction<boolean>>;
  setScanEndMax: React.Dispatch<React.SetStateAction<number>>;
  setScanEndMin: React.Dispatch<React.SetStateAction<number>>;
  setScanEndStep: React.Dispatch<React.SetStateAction<number>>;
  setScanErr: React.Dispatch<React.SetStateAction<string | null>>;
  setScanLoading: React.Dispatch<React.SetStateAction<boolean>>;
  setScanObjective: React.Dispatch<React.SetStateAction<"pnl" | "winrate">>;
  setScanProgress: React.Dispatch<React.SetStateAction<{ done: number; total: number }>>;
  setScanRows: React.Dispatch<React.SetStateAction<EpisodeScanResult[]>>;
  setScanStartMax: React.Dispatch<React.SetStateAction<number>>;
  setScanStartMin: React.Dispatch<React.SetStateAction<number>>;
  setScanStartStep: React.Dispatch<React.SetStateAction<number>>;
  setScanTopK: React.Dispatch<React.SetStateAction<number>>;
  setScannerPresetBusy: React.Dispatch<React.SetStateAction<boolean>>;
  setScannerPresetDraftName: React.Dispatch<React.SetStateAction<string>>;
  setScannerPresetSaveMode: React.Dispatch<React.SetStateAction<boolean>>;
  setScannerPresetStatus: React.Dispatch<React.SetStateAction<string>>;
  setScannerPresets: React.Dispatch<React.SetStateAction<PresetDto[]>>;
  setScopeBenchText: React.Dispatch<React.SetStateAction<string>>;
  setScopeFullscreenPanel: React.Dispatch<React.SetStateAction<ScopePanelKey | null>>;
  setScopeMode: React.Dispatch<React.SetStateAction<"ALL" | "TOP">>;
  setScopeParameterGroupExpanded: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  setScopeResearchDrafts: React.Dispatch<React.SetStateAction<Record<ScopePanelKey, ScopeResearchDraft>>>;
  setScopeResearchFiltersHidden: React.Dispatch<React.SetStateAction<
    Record<ScopePanelKey, { extra: boolean; parallel: boolean }>
  >>;
  setScopeResearchSelections: React.Dispatch<React.SetStateAction<Record<ScopePanelKey, ScopeResearchSelection | null>>>;
  setScopeSelectedParameterKeys: React.Dispatch<React.SetStateAction<string[]>>;
  setSectorEnabled: React.Dispatch<React.SetStateAction<TriMode>>;
  setSelCountries: React.Dispatch<React.SetStateAction<Set<string>>>;
  setSelExchanges: React.Dispatch<React.SetStateAction<Set<string>>>;
  setSelSectors: React.Dispatch<React.SetStateAction<Set<string>>>;
  setSharedRangeFilterModes: React.Dispatch<React.SetStateAction<Record<SharedRangeFilterKey, SharedRangeFilterMode>>>;
  setShowAdvanced: React.Dispatch<React.SetStateAction<boolean>>;
  setShowApply: React.Dispatch<React.SetStateAction<boolean>>;
  setShowIgnore: React.Dispatch<React.SetStateAction<boolean>>;
  setShowPin: React.Dispatch<React.SetStateAction<boolean>>;
  setShowPresets: React.Dispatch<React.SetStateAction<boolean>>;
  setShowSharedMinMax: React.Dispatch<React.SetStateAction<boolean>>;
  setSideFilter: React.Dispatch<React.SetStateAction<"" | "Long" | "Short">>;
  setSizeValue: React.Dispatch<React.SetStateAction<number>>;
  setSizingMode: React.Dispatch<React.SetStateAction<PaperArbSizingMode>>;
  setStartAbs: React.Dispatch<React.SetStateAction<number>>;
  setStartAbsMax: React.Dispatch<React.SetStateAction<string>>;
  setStartCutoffTime: React.Dispatch<React.SetStateAction<string>>;
  setStreamAutoStartLocked: React.Dispatch<React.SetStateAction<boolean>>;
  setStreamAutomationTogglePending: React.Dispatch<React.SetStateAction<null | "start" | "stop">>;
  setStreamSortKey: React.Dispatch<React.SetStateAction<"alpha" | "sigma" | "netEdge">>;
  setStreamWindowCaptureBusy: React.Dispatch<React.SetStateAction<boolean>>;
  setTickersText: React.Dispatch<React.SetStateAction<string>>;
  setTopBenchOn: React.Dispatch<React.SetStateAction<boolean>>;
  setTopMode: React.Dispatch<React.SetStateAction<boolean>>;
  setTopN: React.Dispatch<React.SetStateAction<number>>;
  setTopSigmaOn: React.Dispatch<React.SetStateAction<boolean>>;
  setTopTimeOn: React.Dispatch<React.SetStateAction<boolean>>;
  setUpdatedAt: React.Dispatch<React.SetStateAction<Date | null>>;
  setZapMode: React.Dispatch<React.SetStateAction<ZapMode>>;
};

// Initial values deliberately do NOT live here. A dozen of them are lazy initialisers that read
// component props or helpers (todayNyYmd, streamAutomationConfigOverride, normalizeDilutionStepValue),
// so a static factory cannot produce them. They belong to `useScannerFilters`, which has that scope —
// with the per-strategy overrides coming off the descriptor (startAbs is the only shared field whose
// default differs between the two strategies today).

/**
 * The whole bag as one value. Panels that read dozens of fields take this instead of
 * dozens of props; panels that read a handful still take explicit props.
 */
export type ScannerFilterBag = ScannerFilterState & ScannerFilterSetters;
